# Generated by Django 4.2.2 on 2023-06-07 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('numero_documento', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('email', models.EmailField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('state', models.BooleanField(default=True)),
            ],
        ),
    ]
