# Generated by Django 4.2.2 on 2023-06-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230608_1215'),
    ]

    operations = [
    ]
